name: 新功能请求 (中文)
description: 提交新功能请求
title: "[Feat] "
labels:
  - Enhancement
body:
  - type: checkboxes
    attributes:
      label: 请检查以下事项
      options:
        - label: 我查找过相关的 Issue
          required: false
        - label: 我阅读过[提问的艺术](https://github.com/betaseeker/How-To-Ask-Questions)
          required: false
  - type: textarea
    id: description
    attributes:
      label: 新功能描述
      description: 请详细描述新功能的内容
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 应用版本
      description: 请填写你正在使用的版本
      placeholder: 如 0.0.0.1
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 请填写其他信息
    validations:
      required: false