//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipManager.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipManager.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Document 的本地化字符串。
        /// </summary>
        public static string About_Document {
            get {
                return ResourceManager.GetString("About_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Discussion 的本地化字符串。
        /// </summary>
        public static string About_GithubDiscussion {
            get {
                return ResourceManager.GetString("About_GithubDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Issue 的本地化字符串。
        /// </summary>
        public static string About_GithubIssue {
            get {
                return ResourceManager.GetString("About_GithubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Repo 的本地化字符串。
        /// </summary>
        public static string About_GithubRepo {
            get {
                return ResourceManager.GetString("About_GithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Information 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation {
            get {
                return ResourceManager.GetString("About_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source License 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_OpenSourceLicense {
            get {
                return ResourceManager.GetString("About_MoreInformation_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_Privacy {
            get {
                return ResourceManager.GetString("About_MoreInformation_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager will not upload any of your information. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine1 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager collects all data locally and stores it in the config.json file in the application directory. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine2 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager does not modify the registry. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine3 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added {0} new operation(s) 的本地化字符串。
        /// </summary>
        public static string Action_AddOperation_Toast {
            get {
                return ResourceManager.GetString("Action_AddOperation_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exceptions 的本地化字符串。
        /// </summary>
        public static string Action_Button_Exceptions {
            get {
                return ResourceManager.GetString("Action_Button_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        public static string Action_Command {
            get {
                return ResourceManager.GetString("Action_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string Action_Completed {
            get {
                return ResourceManager.GetString("Action_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Action_ConsoleError {
            get {
                return ResourceManager.GetString("Action_ConsoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No errors detected 的本地化字符串。
        /// </summary>
        public static string Action_ConsoleError_Empty {
            get {
                return ResourceManager.GetString("Action_ConsoleError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string Action_ConsoleOutput {
            get {
                return ResourceManager.GetString("Action_ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No output currently 的本地化字符串。
        /// </summary>
        public static string Action_ConsoleOutput_Empty {
            get {
                return ResourceManager.GetString("Action_ConsoleOutput_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Status 的本地化字符串。
        /// </summary>
        public static string Action_CurrentStatus {
            get {
                return ResourceManager.GetString("Action_CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting in queue 的本地化字符串。
        /// </summary>
        public static string Action_CurrentStatus_WaitingInQueue {
            get {
                return ResourceManager.GetString("Action_CurrentStatus_WaitingInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue 的本地化字符串。
        /// </summary>
        public static string Action_IssueDetected {
            get {
                return ResourceManager.GetString("Action_IssueDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue detected in Action 的本地化字符串。
        /// </summary>
        public static string Action_IssueDetectedToast {
            get {
                return ResourceManager.GetString("Action_IssueDetectedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Current Operations 的本地化字符串。
        /// </summary>
        public static string Action_NoCurrentOperations {
            get {
                return ResourceManager.GetString("Action_NoCurrentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Action_Operation_Download {
            get {
                return ResourceManager.GetString("Action_Operation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Install 的本地化字符串。
        /// </summary>
        public static string Action_Operation_Install {
            get {
                return ResourceManager.GetString("Action_Operation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Install (via requirements.txt) 的本地化字符串。
        /// </summary>
        public static string Action_Operation_InstallByRequirements {
            get {
                return ResourceManager.GetString("Action_Operation_InstallByRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Uninstallation 的本地化字符串。
        /// </summary>
        public static string Action_Operation_Uninstall {
            get {
                return ResourceManager.GetString("Action_Operation_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Update 的本地化字符串。
        /// </summary>
        public static string Action_Operation_Update {
            get {
                return ResourceManager.GetString("Action_Operation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string ActionException_Badge_Timestamp {
            get {
                return ResourceManager.GetString("ActionException_Badge_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exceptions 的本地化字符串。
        /// </summary>
        public static string ActionException_Header {
            get {
                return ResourceManager.GetString("ActionException_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No package {0} with version strictly equal to {1} was found, please check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_ArbitraryEquality {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_ArbitraryEquality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No compatible packages {0} with at least version {1} were found, check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_Compatible {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_Compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No packages {0} with version less than {1} were found, please check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_ExclusiveOrderedLess {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_ExclusiveOrderedLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No package {0} with version greater than {1} was found, please check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_ExclusiveOrderedMore {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_ExclusiveOrderedMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No package {0} with version less than or equal to {1} was found, please check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_InclusiveOrderedLess {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_InclusiveOrderedLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No package {0} with version greater than or equal to {1} was found, please check that the package name is spelled correctly and that the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_InclusiveOrderedMore {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_InclusiveOrderedMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package {0} with version {1} was not found, check the spelling of the package name and make sure the package (and its version) exists. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionAnalyze_NoMatchingDistFound_VersionMatching {
            get {
                return ResourceManager.GetString("ActionExceptionAnalyze_NoMatchingDistFound_VersionMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please copy the error message to find a solution. 的本地化字符串。
        /// </summary>
        public static string ActionExceptionWindow_CopyToClipboard {
            get {
                return ResourceManager.GetString("ActionExceptionWindow_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception 的本地化字符串。
        /// </summary>
        public static string ActionExceptionWindow_Exception {
            get {
                return ResourceManager.GetString("ActionExceptionWindow_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speculation 的本地化字符串。
        /// </summary>
        public static string ActionExceptionWindow_Speculation {
            get {
                return ResourceManager.GetString("ActionExceptionWindow_Speculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Exception 的本地化字符串。
        /// </summary>
        public static string ActionExceptionWindow_Title {
            get {
                return ResourceManager.GetString("ActionExceptionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Common_Button_Refresh {
            get {
                return ResourceManager.GetString("Common_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caution 的本地化字符串。
        /// </summary>
        public static string Common_NoticeTitle_Caution {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string Common_NoticeTitle_Notice {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ContentDialog_CloseButton_Cancel {
            get {
                return ResourceManager.GetString("ContentDialog_CloseButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are still running background tasks. Do you confirm to exit the software? 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_ActionStillRunning {
            get {
                return ResourceManager.GetString("ContentDialog_Message_ActionStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment already exists 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentAlreadyExists {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment not available 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentCheckFailed {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment available 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentCheckPassed {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The environment will be removed from the list 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in adding environment 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentInvaild {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The environment is up to date 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentIsLatest {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You didn&apos;t choose an environment 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_EnvironmentNoSelection {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version detected. Update now? 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_FindUpdate {
            get {
                return ResourceManager.GetString("ContentDialog_Message_FindUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Following packages will be removed from the environment: 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_LibraryDeletionWarning {
            get {
                return ResourceManager.GetString("ContentDialog_Message_LibraryDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Error 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_NetworkError {
            get {
                return ResourceManager.GetString("ContentDialog_Message_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package(s) are up to date 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Message_PackageIsLatest {
            get {
                return ResourceManager.GetString("ContentDialog_Message_PackageIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string ContentDialog_PrimaryButton_Action {
            get {
                return ResourceManager.GetString("ContentDialog_PrimaryButton_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Environment 的本地化字符串。
        /// </summary>
        public static string ContentDialog_PrimaryButton_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("ContentDialog_PrimaryButton_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Warning 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Title_AreYouSure {
            get {
                return ResourceManager.GetString("ContentDialog_Title_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Title_Error {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Title_Notice {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Title_Success {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string ContentDialog_Title_Warning {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developing 的本地化字符串。
        /// </summary>
        public static string Development_Developing {
            get {
                return ResourceManager.GetString("Development_Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Environment 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_AddEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_AddEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_CheckEnvironmentUpdate {
            get {
                return ResourceManager.GetString("Environment_Operation_CheckEnvironmentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Environment (from list) 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_RemoveEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_RemoveEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Environment 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_VerifyEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_VerifyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected Environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find any environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_NotFound {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment Variables 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Pip command 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you are using &quot;pip install&quot;, type &quot;pip&quot; in the box. Similarly, for &quot;pip3.11 install&quot;, type &quot;pip3.11&quot;. 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Notice {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Command 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the absolute path of python.exe 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python Executable Path 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager - Unexpected Exception 的本地化字符串。
        /// </summary>
        public static string ExceptionWindow_Title {
            get {
                return ResourceManager.GetString("ExceptionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current: {0} 的本地化字符串。
        /// </summary>
        public static string Library_CheckUpdate_Current {
            get {
                return ResourceManager.GetString("Library_CheckUpdate_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest: {0} 的本地化字符串。
        /// </summary>
        public static string Library_CheckUpdate_Latest {
            get {
                return ResourceManager.GetString("Library_CheckUpdate_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} package(s) found 的本地化字符串。
        /// </summary>
        public static string Library_Data_PackageFound {
            get {
                return ResourceManager.GetString("Library_Data_PackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} item(s) selected 的本地化字符串。
        /// </summary>
        public static string Library_Data_SelectedItemsCount {
            get {
                return ResourceManager.GetString("Library_Data_SelectedItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add environment 的本地化字符串。
        /// </summary>
        public static string Library_Error_AddEnvironment {
            get {
                return ResourceManager.GetString("Library_Error_AddEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Environment 的本地化字符串。
        /// </summary>
        public static string Library_Error_NoEnvironment {
            get {
                return ResourceManager.GetString("Library_Error_NoEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string Library_Operation_CheckUpdate {
            get {
                return ResourceManager.GetString("Library_Operation_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Delete {
            get {
                return ResourceManager.GetString("Library_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Details {
            get {
                return ResourceManager.GetString("Library_Operation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Install {
            get {
                return ResourceManager.GetString("Library_Operation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dev 的本地化字符串。
        /// </summary>
        public static string Library_Version_Dev {
            get {
                return ResourceManager.GetString("Library_Version_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post 的本地化字符串。
        /// </summary>
        public static string Library_Version_Post {
            get {
                return ResourceManager.GetString("Library_Version_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unstable 的本地化字符串。
        /// </summary>
        public static string Library_Version_Pre {
            get {
                return ResourceManager.GetString("Library_Version_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development Status 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_DevelopmentStatus {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_DevelopmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_Environment {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intended Audience 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Service 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_CustomerService {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developers 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Developers {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Education 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Education {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Users &amp; Desktop 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_EndUsersDesktop {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_EndUsersDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Financial and Insurance Industry 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_FinancialAndInsuranceIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_FinancialAndInsuranceIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healthcare Industry 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_HealthcareIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_HealthcareIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information Technology 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_InformationTechonology {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_InformationTechonology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legal Industry 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_LegalIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_LegalIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturing 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Manufacturing {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_OtherAudience {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_OtherAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Religion 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Religion {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Science &amp; Research 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_ScienceResearch {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_ScienceResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Administrators 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_SystemAdministrators {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_SystemAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telecommunications Industry 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_TelecommunicationsIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_TelecommunicationsIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operating System 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_OperatingSystem {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OS Independent 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_OperatingSystem_OSIndependent {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_OperatingSystem_OSIndependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Programming Language 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_ProgrammingLanguage {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_ProgrammingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classifier 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_Title {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Topic 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Classifier_Topic {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Contact_Author {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Contact_AuthorEmail {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Url 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Contact_ProjectUrl {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Contact_Title {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Header {
            get {
                return ResourceManager.GetString("LibraryDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Package {
            get {
                return ResourceManager.GetString("LibraryDetail_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Path {
            get {
                return ResourceManager.GetString("LibraryDetail_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Summary {
            get {
                return ResourceManager.GetString("LibraryDetail_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Unknown {
            get {
                return ResourceManager.GetString("LibraryDetail_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string LibraryDetail_Version {
            get {
                return ResourceManager.GetString("LibraryDetail_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package already in list 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_AlreadyInList {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_AlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package already installed 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_AlreadyInstalled {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Package Name (PEP 508) 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_InvalidPackageName {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_InvalidPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Package Name 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_Notice {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package not found 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_PackageNotFound {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verifying 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Add_Verifying {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Distributions 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Download_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Download_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The newest and compatible version will be installed 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_List_DefaultVersion {
            get {
                return ResourceManager.GetString("LibraryInstall_List_DefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version Specified 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_List_VersionSpecified {
            get {
                return ResourceManager.GetString("LibraryInstall_List_VersionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Requirements_Download {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download dependencies 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Requirements_DownloadDependencies {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_DownloadDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Folder 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Requirements_DownloadFolder {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 requirements.txt Import 的本地化字符串。
        /// </summary>
        public static string LibraryInstall_Requirements_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Action {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Environment {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lab 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Lab {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Library {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Search {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Tools {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Mask_Loading {
            get {
                return ResourceManager.GetString("Mask_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The newest and compatible version will be selected 的本地化字符串。
        /// </summary>
        public static string Search_DefaultVersion {
            get {
                return ResourceManager.GetString("Search_DefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify Version 的本地化字符串。
        /// </summary>
        public static string Search_VersionSpecified {
            get {
                return ResourceManager.GetString("Search_VersionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string Settings_Category_FileManagement {
            get {
                return ResourceManager.GetString("Settings_Category_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Source 的本地化字符串。
        /// </summary>
        public static string Settings_Category_PackageSource {
            get {
                return ResourceManager.GetString("Settings_Category_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string Settings_Category_Personalization {
            get {
                return ResourceManager.GetString("Settings_Category_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes folder not found 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_CrushesDirNotFound {
            get {
                return ResourceManager.GetString("Settings_FileManagement_CrushesDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenAppDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenAppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Crushes Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenCrushesDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenCrushesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenLogDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Config 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action will delete all app-related settings. Are you sure you want to keep going with this? 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig_DialogContent {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig_DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aliyun 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Aliyun {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Aliyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Douban 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Douban {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Douban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Network 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTest {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Error 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTestFailed {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTesting {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PyPI source contains the most complete library, but the connection is slow.
        ///Other sources are faster to connect to, but may be incomplete. 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Notice {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PyPI Official 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Official {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tsinghua 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Tsinghua {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Tsinghua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crush files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationCrushesAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationCrushesAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationLogAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationLogAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Dark {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Light {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_CrushesAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_CrushesAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Language {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_LogAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_LogAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Theme {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes will take effect after the application is restarted 的本地化字符串。
        /// </summary>
        public static string Snackbar_effectAfterRestart {
            get {
                return ResourceManager.GetString("Snackbar_effectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Package 的本地化字符串。
        /// </summary>
        public static string TrayMenu_Install {
            get {
                return ResourceManager.GetString("TrayMenu_Install", resourceCulture);
            }
        }
    }
}
