//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipManager.Desktop.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipManager.Desktop.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Page_Settings_Language_Subtitle {
            get {
                return ResourceManager.GetString("Page_Settings_Language_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Page_Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Page_Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Page_Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Page_Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Page_Settings_Theme_Subtitle {
            get {
                return ResourceManager.GetString("Page_Settings_Theme_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Page_Settings_UserMode_Advanced {
            get {
                return ResourceManager.GetString("Page_Settings_UserMode_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides full access to all parameters for maximum customization..
        /// </summary>
        internal static string Page_Settings_UserMode_Advanced_Tips {
            get {
                return ResourceManager.GetString("Page_Settings_UserMode_Advanced_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string Page_Settings_UserMode_Beginner {
            get {
                return ResourceManager.GetString("Page_Settings_UserMode_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focuses on basic AI functionality with minimal parameter adjustments..
        /// </summary>
        internal static string Page_Settings_UserMode_Beginner_Tips {
            get {
                return ResourceManager.GetString("Page_Settings_UserMode_Beginner_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode.
        /// </summary>
        internal static string Page_Settings_UserMode_Subtitle {
            get {
                return ResourceManager.GetString("Page_Settings_UserMode_Subtitle", resourceCulture);
            }
        }
    }
}
