//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipManager.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipManager.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Document 的本地化字符串。
        /// </summary>
        public static string About_Document {
            get {
                return ResourceManager.GetString("About_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Discussion 的本地化字符串。
        /// </summary>
        public static string About_GithubDiscussion {
            get {
                return ResourceManager.GetString("About_GithubDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Issue 的本地化字符串。
        /// </summary>
        public static string About_GithubIssue {
            get {
                return ResourceManager.GetString("About_GithubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github Repo 的本地化字符串。
        /// </summary>
        public static string About_GithubRepo {
            get {
                return ResourceManager.GetString("About_GithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Information 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation {
            get {
                return ResourceManager.GetString("About_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source License 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_OpenSourceLicense {
            get {
                return ResourceManager.GetString("About_MoreInformation_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_Privacy {
            get {
                return ResourceManager.GetString("About_MoreInformation_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager will not upload any of your information. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine1 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager collects all data locally and stores it in the config.json file in the application directory. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine2 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Manager does not modify the registry. 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation_PrivacyLine3 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Common_Button_Refresh {
            get {
                return ResourceManager.GetString("Common_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caution 的本地化字符串。
        /// </summary>
        public static string Common_NoticeTitle_Caution {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        public static string Common_NoticeTitle_Notice {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Environment 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_AddEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_AddEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Environment (from list) 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_RemoveEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_RemoveEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Environment 的本地化字符串。
        /// </summary>
        public static string Environment_Operation_VerifyEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_VerifyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected Environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find any environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_NotFound {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment Variables 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Environment 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Pip command 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you are using &quot;pip install&quot;, type &quot;pip&quot; in the box. Similarly, for &quot;pip3.11 install&quot;, type &quot;pip3.11&quot;. 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Notice {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pip Command 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the absolute path of python.exe 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python Executable Path 的本地化字符串。
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  package(s) found 的本地化字符串。
        /// </summary>
        public static string Library_Data_PackageFound {
            get {
                return ResourceManager.GetString("Library_Data_PackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string Library_Operation_CheckUpdate {
            get {
                return ResourceManager.GetString("Library_Operation_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Delete {
            get {
                return ResourceManager.GetString("Library_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Information {
            get {
                return ResourceManager.GetString("Library_Operation_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Library_Operation_Install {
            get {
                return ResourceManager.GetString("Library_Operation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Environment {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Library {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Search {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Tools {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string MsgBox_CloseButton_Cancel {
            get {
                return ResourceManager.GetString("MsgBox_CloseButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment already exists 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentAlreadyExists {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment not available 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentCheckFailed {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment available 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentCheckPassed {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The environment will be removed from the list 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in adding environment 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentInvaild {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You didn&apos;t choose an environment 的本地化字符串。
        /// </summary>
        public static string MsgBox_Message_EnvironmentNoSelection {
            get {
                return ResourceManager.GetString("MsgBox_Message_EnvironmentNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string MsgBox_PrimaryButton_Action {
            get {
                return ResourceManager.GetString("MsgBox_PrimaryButton_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Environment 的本地化字符串。
        /// </summary>
        public static string MsgBox_PrimaryButton_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("MsgBox_PrimaryButton_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Warning 的本地化字符串。
        /// </summary>
        public static string MsgBox_Title_AreYouSure {
            get {
                return ResourceManager.GetString("MsgBox_Title_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string MsgBox_Title_Error {
            get {
                return ResourceManager.GetString("MsgBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string MsgBox_Title_Success {
            get {
                return ResourceManager.GetString("MsgBox_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string MsgBox_Title_Warning {
            get {
                return ResourceManager.GetString("MsgBox_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string Settings_Category_FileManagement {
            get {
                return ResourceManager.GetString("Settings_Category_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package Source 的本地化字符串。
        /// </summary>
        public static string Settings_Category_PackageSource {
            get {
                return ResourceManager.GetString("Settings_Category_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string Settings_Category_Personalization {
            get {
                return ResourceManager.GetString("Settings_Category_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes folder not found 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_CrushesDirNotFound {
            get {
                return ResourceManager.GetString("Settings_FileManagement_CrushesDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenAppDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenAppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Crushes Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenCrushesDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenCrushesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenLogDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Config 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action will delete all app-related settings. Are you sure you want to keep going with this? 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig_DialogContent {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig_DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aliyun 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Aliyun {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Aliyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Douban 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Douban {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Douban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Network 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTest {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Error 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTestFailed {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Testing 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_NetworkTesting {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PyPI source contains the most complete library, but the connection is slow.
        ///Other sources are faster to connect to, but may be incomplete. 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Notice {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PyPI Official 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Official {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tsinghua 的本地化字符串。
        /// </summary>
        public static string Settings_PackageSource_Tsinghua {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Tsinghua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crush files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationCrushesAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationCrushesAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationLogAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationLogAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Dark {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Light {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_CrushesAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_CrushesAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Language {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_LogAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_LogAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Theme {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes will take effect after the application is restarted 的本地化字符串。
        /// </summary>
        public static string Snackbar_effectAfterRestart {
            get {
                return ResourceManager.GetString("Snackbar_effectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Package 的本地化字符串。
        /// </summary>
        public static string TrayMenu_Install {
            get {
                return ResourceManager.GetString("TrayMenu_Install", resourceCulture);
            }
        }
    }
}
