//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipManager.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipManager.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 More Information 的本地化字符串。
        /// </summary>
        public static string About_MoreInformation {
            get {
                return ResourceManager.GetString("About_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Environment {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Library {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Search {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationContent_Tools {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string MessageDialog_CloseButton_Cancel {
            get {
                return ResourceManager.GetString("MessageDialog_CloseButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        public static string MessageDialog_PrimaryButton_Action {
            get {
                return ResourceManager.GetString("MessageDialog_PrimaryButton_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Warning 的本地化字符串。
        /// </summary>
        public static string MessageDialog_Title_AreYouSure {
            get {
                return ResourceManager.GetString("MessageDialog_Title_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string Settings_Category_FileManagement {
            get {
                return ResourceManager.GetString("Settings_Category_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        public static string Settings_Category_Personalization {
            get {
                return ResourceManager.GetString("Settings_Category_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes folder not found 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_CrushesDirNotFound {
            get {
                return ResourceManager.GetString("Settings_FileManagement_CrushesDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenAppDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenAppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Crushes Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenCrushesDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenCrushesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log Folder 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_OpenLogDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Config 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action will delete all app-related settings. Are you sure you want to keep going with this? 的本地化字符串。
        /// </summary>
        public static string Settings_FileManagement_ResetConfig_DialogContent {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig_DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crush files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationCrushesAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationCrushesAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log files will be deleted after more than {0} 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationLogAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationLogAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Dark {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTheme_Light {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crushes Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_CrushesAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_CrushesAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Language {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Auto Deletion 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_LogAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_LogAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Settings_PersonalizationTitle_Theme {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caution 的本地化字符串。
        /// </summary>
        public static string Snackbar_Caution {
            get {
                return ResourceManager.GetString("Snackbar_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes will take effect after the application is restarted 的本地化字符串。
        /// </summary>
        public static string Snackbar_effectAfterRestart {
            get {
                return ResourceManager.GetString("Snackbar_effectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Package 的本地化字符串。
        /// </summary>
        public static string TrayMenu_Install {
            get {
                return ResourceManager.GetString("TrayMenu_Install", resourceCulture);
            }
        }
    }
}
