//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipManager.Windows.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipManager.Windows.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string About_Document {
            get {
                return ResourceManager.GetString("About_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Discussion.
        /// </summary>
        public static string About_GithubDiscussion {
            get {
                return ResourceManager.GetString("About_GithubDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Issue.
        /// </summary>
        public static string About_GithubIssue {
            get {
                return ResourceManager.GetString("About_GithubIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Repo.
        /// </summary>
        public static string About_GithubRepo {
            get {
                return ResourceManager.GetString("About_GithubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string About_MoreInformation {
            get {
                return ResourceManager.GetString("About_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source License.
        /// </summary>
        public static string About_MoreInformation_OpenSourceLicense {
            get {
                return ResourceManager.GetString("About_MoreInformation_OpenSourceLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string About_MoreInformation_Privacy {
            get {
                return ResourceManager.GetString("About_MoreInformation_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip Manager will not upload any of your information..
        /// </summary>
        public static string About_MoreInformation_PrivacyLine1 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip Manager collects all data locally and stores it in the config.json file in the application directory..
        /// </summary>
        public static string About_MoreInformation_PrivacyLine2 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip Manager does not modify the registry..
        /// </summary>
        public static string About_MoreInformation_PrivacyLine3 {
            get {
                return ResourceManager.GetString("About_MoreInformation_PrivacyLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} new operation(s).
        /// </summary>
        public static string Action_AddOperation_Toast {
            get {
                return ResourceManager.GetString("Action_AddOperation_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string Action_Button_Exceptions {
            get {
                return ResourceManager.GetString("Action_Button_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Action_Command {
            get {
                return ResourceManager.GetString("Action_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Action_Completed {
            get {
                return ResourceManager.GetString("Action_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Action_ConsoleError {
            get {
                return ResourceManager.GetString("Action_ConsoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors detected.
        /// </summary>
        public static string Action_ConsoleError_Empty {
            get {
                return ResourceManager.GetString("Action_ConsoleError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Action_ConsoleOutput {
            get {
                return ResourceManager.GetString("Action_ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string Action_CurrentStatus {
            get {
                return ResourceManager.GetString("Action_CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting in queue.
        /// </summary>
        public static string Action_CurrentStatus_WaitingInQueue {
            get {
                return ResourceManager.GetString("Action_CurrentStatus_WaitingInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Action_IssueDetected {
            get {
                return ResourceManager.GetString("Action_IssueDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue detected in Action.
        /// </summary>
        public static string Action_IssueDetectedToast {
            get {
                return ResourceManager.GetString("Action_IssueDetectedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Current Operations.
        /// </summary>
        public static string Action_NoCurrentOperations {
            get {
                return ResourceManager.GetString("Action_NoCurrentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Operation_Cancel {
            get {
                return ResourceManager.GetString("Action_Operation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Action_Operation_Download {
            get {
                return ResourceManager.GetString("Action_Operation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Install.
        /// </summary>
        public static string Action_Operation_Install {
            get {
                return ResourceManager.GetString("Action_Operation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Install (via requirements.txt).
        /// </summary>
        public static string Action_Operation_InstallByRequirements {
            get {
                return ResourceManager.GetString("Action_Operation_InstallByRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Uninstallation.
        /// </summary>
        public static string Action_Operation_Uninstall {
            get {
                return ResourceManager.GetString("Action_Operation_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Update.
        /// </summary>
        public static string Action_Operation_Update {
            get {
                return ResourceManager.GetString("Action_Operation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel.
        /// </summary>
        public static string Action_OperationCanceled_Failed {
            get {
                return ResourceManager.GetString("Action_OperationCanceled_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Cancelled.
        /// </summary>
        public static string Action_OperationCanceled_Success {
            get {
                return ResourceManager.GetString("Action_OperationCanceled_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ActionException_Badge_Timestamp {
            get {
                return ResourceManager.GetString("ActionException_Badge_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Search.
        /// </summary>
        public static string ActionException_BingSearch {
            get {
                return ResourceManager.GetString("ActionException_BingSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string ActionException_CopyToClipboard {
            get {
                return ResourceManager.GetString("ActionException_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string ActionException_CopyToClipboardNotice {
            get {
                return ResourceManager.GetString("ActionException_CopyToClipboardNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ActionException_Exception {
            get {
                return ResourceManager.GetString("ActionException_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Search.
        /// </summary>
        public static string ActionException_GoogleSearch {
            get {
                return ResourceManager.GetString("ActionException_GoogleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string ActionException_Operation {
            get {
                return ResourceManager.GetString("ActionException_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Button_Add {
            get {
                return ResourceManager.GetString("Common_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Common_Button_Browse {
            get {
                return ResourceManager.GetString("Common_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Common_Button_Refresh {
            get {
                return ResourceManager.GetString("Common_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        public static string Common_NoticeTitle_Caution {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Common_NoticeTitle_Notice {
            get {
                return ResourceManager.GetString("Common_NoticeTitle_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ContentDialog_CloseButton_Cancel {
            get {
                return ResourceManager.GetString("ContentDialog_CloseButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are still running background tasks. Do you confirm to exit the software?.
        /// </summary>
        public static string ContentDialog_Message_ActionStillRunning {
            get {
                return ResourceManager.GetString("ContentDialog_Message_ActionStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Caches Cleared.
        /// </summary>
        public static string ContentDialog_Message_CacheCleared {
            get {
                return ResourceManager.GetString("ContentDialog_Message_CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clear caches.
        /// </summary>
        public static string ContentDialog_Message_CacheClearFailed {
            get {
                return ResourceManager.GetString("ContentDialog_Message_CacheClearFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment already exists.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentAlreadyExists {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment not available.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentCheckFailed {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment available.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentCheckPassed {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment will be removed from the list.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in adding environment.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentInvaild {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment is up to date.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentIsLatest {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t choose an environment.
        /// </summary>
        public static string ContentDialog_Message_EnvironmentNoSelection {
            get {
                return ResourceManager.GetString("ContentDialog_Message_EnvironmentNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected. Update now?.
        /// </summary>
        public static string ContentDialog_Message_FindUpdate {
            get {
                return ResourceManager.GetString("ContentDialog_Message_FindUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following packages will be removed from the environment:.
        /// </summary>
        public static string ContentDialog_Message_LibraryDeletionWarning {
            get {
                return ResourceManager.GetString("ContentDialog_Message_LibraryDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string ContentDialog_Message_NetworkError {
            get {
                return ResourceManager.GetString("ContentDialog_Message_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package(s) are up to date.
        /// </summary>
        public static string ContentDialog_Message_PackageIsLatest {
            get {
                return ResourceManager.GetString("ContentDialog_Message_PackageIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ContentDialog_PrimaryButton_Action {
            get {
                return ResourceManager.GetString("ContentDialog_PrimaryButton_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Environment.
        /// </summary>
        public static string ContentDialog_PrimaryButton_EnvironmentDeletion {
            get {
                return ResourceManager.GetString("ContentDialog_PrimaryButton_EnvironmentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Warning.
        /// </summary>
        public static string ContentDialog_Title_AreYouSure {
            get {
                return ResourceManager.GetString("ContentDialog_Title_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ContentDialog_Title_Error {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string ContentDialog_Title_Notice {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ContentDialog_Title_Success {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ContentDialog_Title_Warning {
            get {
                return ResourceManager.GetString("ContentDialog_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing.
        /// </summary>
        public static string Development_Developing {
            get {
                return ResourceManager.GetString("Development_Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open download folder (for wheel files).
        /// </summary>
        public static string Dialog_Title_DownloadDistributions {
            get {
                return ResourceManager.GetString("Dialog_Title_DownloadDistributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Environment.
        /// </summary>
        public static string Environment_Operation_AddEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_AddEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string Environment_Operation_CheckEnvironmentUpdate {
            get {
                return ResourceManager.GetString("Environment_Operation_CheckEnvironmentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string Environment_Operation_ClearEnvironmentCache {
            get {
                return ResourceManager.GetString("Environment_Operation_ClearEnvironmentCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string Environment_Operation_RemoveEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_RemoveEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Availability.
        /// </summary>
        public static string Environment_Operation_VerifyEnvironment {
            get {
                return ResourceManager.GetString("Environment_Operation_VerifyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Environment.
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any environment.
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_NotFound {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        public static string EnvironmentAdd_EnvironmentVariable_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_EnvironmentVariable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Environment.
        /// </summary>
        public static string EnvironmentAdd_Header {
            get {
                return ResourceManager.GetString("EnvironmentAdd_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pip command.
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using &quot;pip install&quot;, type &quot;pip&quot; in the box. Similarly, for &quot;pip3.11 install&quot;, type &quot;pip3.11&quot;..
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Notice {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip Command.
        /// </summary>
        public static string EnvironmentAdd_PipCommand_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PipCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the absolute path of python.exe.
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Label {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Executable Path.
        /// </summary>
        public static string EnvironmentAdd_PythonPath_Title {
            get {
                return ResourceManager.GetString("EnvironmentAdd_PythonPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: .
        /// </summary>
        public static string EnvironmentCheckEnvironmentUpdate_CurrentVersion {
            get {
                return ResourceManager.GetString("EnvironmentCheckEnvironmentUpdate_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: .
        /// </summary>
        public static string EnvironmentCheckEnvironmentUpdate_LatestVersion {
            get {
                return ResourceManager.GetString("EnvironmentCheckEnvironmentUpdate_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pip Manager - Unexpected Exception.
        /// </summary>
        public static string ExceptionWindow_Title {
            get {
                return ResourceManager.GetString("ExceptionWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: {0}.
        /// </summary>
        public static string Library_CheckUpdate_Current {
            get {
                return ResourceManager.GetString("Library_CheckUpdate_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: {0}.
        /// </summary>
        public static string Library_CheckUpdate_Latest {
            get {
                return ResourceManager.GetString("Library_CheckUpdate_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} package(s) found.
        /// </summary>
        public static string Library_Data_PackageFound {
            get {
                return ResourceManager.GetString("Library_Data_PackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s used.
        /// </summary>
        public static string Library_Data_RefreshTimeUsage {
            get {
                return ResourceManager.GetString("Library_Data_RefreshTimeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s) selected.
        /// </summary>
        public static string Library_Data_SelectedItemsCount {
            get {
                return ResourceManager.GetString("Library_Data_SelectedItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add environment.
        /// </summary>
        public static string Library_Error_AddEnvironment {
            get {
                return ResourceManager.GetString("Library_Error_AddEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Environment.
        /// </summary>
        public static string Library_Error_NoEnvironment {
            get {
                return ResourceManager.GetString("Library_Error_NoEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string Library_Operation_CheckUpdate {
            get {
                return ResourceManager.GetString("Library_Operation_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Library_Operation_Delete {
            get {
                return ResourceManager.GetString("Library_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Library_Operation_Details {
            get {
                return ResourceManager.GetString("Library_Operation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Library_Operation_Install {
            get {
                return ResourceManager.GetString("Library_Operation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.
        /// </summary>
        public static string Library_Version_Dev {
            get {
                return ResourceManager.GetString("Library_Version_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Library_Version_Post {
            get {
                return ResourceManager.GetString("Library_Version_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable.
        /// </summary>
        public static string Library_Version_Pre {
            get {
                return ResourceManager.GetString("Library_Version_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Status.
        /// </summary>
        public static string LibraryDetail_Classifier_DevelopmentStatus {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_DevelopmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string LibraryDetail_Classifier_Environment {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended Audience.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_CustomerService {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Developers {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Education {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Users &amp; Desktop.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_EndUsersDesktop {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_EndUsersDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial and Insurance Industry.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_FinancialAndInsuranceIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_FinancialAndInsuranceIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthcare Industry.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_HealthcareIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_HealthcareIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_InformationTechonology {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_InformationTechonology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Industry.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_LegalIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_LegalIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Manufacturing {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_OtherAudience {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_OtherAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_Religion {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science &amp; Research.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_ScienceResearch {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_ScienceResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrators.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_SystemAdministrators {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_SystemAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecommunications Industry.
        /// </summary>
        public static string LibraryDetail_Classifier_IntendedAudience_TelecommunicationsIndustry {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_IntendedAudience_TelecommunicationsIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string LibraryDetail_Classifier_OperatingSystem {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Independent.
        /// </summary>
        public static string LibraryDetail_Classifier_OperatingSystem_OSIndependent {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_OperatingSystem_OSIndependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Language.
        /// </summary>
        public static string LibraryDetail_Classifier_ProgrammingLanguage {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_ProgrammingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string LibraryDetail_Classifier_Topic {
            get {
                return ResourceManager.GetString("LibraryDetail_Classifier_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string LibraryDetail_Contact_Author {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LibraryDetail_Contact_AuthorEmail {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Url.
        /// </summary>
        public static string LibraryDetail_Contact_ProjectUrl {
            get {
                return ResourceManager.GetString("LibraryDetail_Contact_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} dependency packages.
        /// </summary>
        public static string LibraryDetail_Dependency_Caption {
            get {
                return ResourceManager.GetString("LibraryDetail_Dependency_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dependency packages required.
        /// </summary>
        public static string LibraryDetail_Dependency_Empty {
            get {
                return ResourceManager.GetString("LibraryDetail_Dependency_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string LibraryDetail_Dependency_Header {
            get {
                return ResourceManager.GetString("LibraryDetail_Dependency_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string LibraryDetail_Header {
            get {
                return ResourceManager.GetString("LibraryDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string LibraryDetail_Package {
            get {
                return ResourceManager.GetString("LibraryDetail_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string LibraryDetail_Path {
            get {
                return ResourceManager.GetString("LibraryDetail_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string LibraryDetail_Summary {
            get {
                return ResourceManager.GetString("LibraryDetail_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Not Found.
        /// </summary>
        public static string LibraryDetail_Toast_PackageNotFound {
            get {
                return ResourceManager.GetString("LibraryDetail_Toast_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string LibraryDetail_Unknown {
            get {
                return ResourceManager.GetString("LibraryDetail_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LibraryDetail_Version {
            get {
                return ResourceManager.GetString("LibraryDetail_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package already in list.
        /// </summary>
        public static string LibraryInstall_Add_AlreadyInList {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_AlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package already installed.
        /// </summary>
        public static string LibraryInstall_Add_AlreadyInstalled {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string LibraryInstall_Add_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Package Name (PEP 508).
        /// </summary>
        public static string LibraryInstall_Add_InvalidPackageName {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_InvalidPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Package Name.
        /// </summary>
        public static string LibraryInstall_Add_Notice {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package not found.
        /// </summary>
        public static string LibraryInstall_Add_PackageNotFound {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying.
        /// </summary>
        public static string LibraryInstall_Add_Verifying {
            get {
                return ResourceManager.GetString("LibraryInstall_Add_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Distributions.
        /// </summary>
        public static string LibraryInstall_Download_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Download_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string LibraryInstall_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution File already added to the list.
        /// </summary>
        public static string LibraryInstall_InstallDistributions_AlreadyExists {
            get {
                return ResourceManager.GetString("LibraryInstall_InstallDistributions_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install via distributions.
        /// </summary>
        public static string LibraryInstall_InstallDistributions_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_InstallDistributions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install dependencies.
        /// </summary>
        public static string LibraryInstall_InstallDistributions_InstallDependencies {
            get {
                return ResourceManager.GetString("LibraryInstall_InstallDistributions_InstallDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Distribution File.
        /// </summary>
        public static string LibraryInstall_InstallDistributions_InvalidFile {
            get {
                return ResourceManager.GetString("LibraryInstall_InstallDistributions_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading a file, check if the file is occupied.
        /// </summary>
        public static string LibraryInstall_InstallDistributions_IOError {
            get {
                return ResourceManager.GetString("LibraryInstall_InstallDistributions_IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newest and compatible version will be installed.
        /// </summary>
        public static string LibraryInstall_List_DefaultVersion {
            get {
                return ResourceManager.GetString("LibraryInstall_List_DefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Specified.
        /// </summary>
        public static string LibraryInstall_List_VersionSpecified {
            get {
                return ResourceManager.GetString("LibraryInstall_List_VersionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string LibraryInstall_Requirements_Download {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download dependencies.
        /// </summary>
        public static string LibraryInstall_Requirements_DownloadDependencies {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_DownloadDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Folder.
        /// </summary>
        public static string LibraryInstall_Requirements_DownloadFolder {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_DownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requirements.txt Import.
        /// </summary>
        public static string LibraryInstall_Requirements_Header {
            get {
                return ResourceManager.GetString("LibraryInstall_Requirements_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_NavigationContent_About {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string MainWindow_NavigationContent_Action {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string MainWindow_NavigationContent_Environment {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string MainWindow_NavigationContent_Lab {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainWindow_NavigationContent_Library {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string MainWindow_NavigationContent_Scenario {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MainWindow_NavigationContent_Search {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_NavigationContent_Settings {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainWindow_NavigationContent_Tools {
            get {
                return ResourceManager.GetString("MainWindow_NavigationContent_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Mask_Loading {
            get {
                return ResourceManager.GetString("Mask_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Overlay_Button_Cancel {
            get {
                return ResourceManager.GetString("Overlay_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Overlay_Button_Update {
            get {
                return ResourceManager.GetString("Overlay_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Versions Found.
        /// </summary>
        public static string Overlay_Title_PackageUpdate {
            get {
                return ResourceManager.GetString("Overlay_Title_PackageUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newest and compatible version will be selected.
        /// </summary>
        public static string Search_DefaultVersion {
            get {
                return ResourceManager.GetString("Search_DefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Description.
        /// </summary>
        public static string Search_List_NoDescription {
            get {
                return ResourceManager.GetString("Search_List_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} results found.
        /// </summary>
        public static string Search_List_TotalResultNumber {
            get {
                return ResourceManager.GetString("Search_List_TotalResultNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time: .
        /// </summary>
        public static string Search_List_UpdateTime {
            get {
                return ResourceManager.GetString("Search_List_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Search_Operation_Details {
            get {
                return ResourceManager.GetString("Search_Operation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string Search_Query_NoResults {
            get {
                return ResourceManager.GetString("Search_Query_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Search_Query_Timeout {
            get {
                return ResourceManager.GetString("Search_Query_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Version.
        /// </summary>
        public static string Search_VersionSpecified {
            get {
                return ResourceManager.GetString("Search_VersionSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Distributions.
        /// </summary>
        public static string SearchDetail_DownloadDistributions {
            get {
                return ResourceManager.GetString("SearchDetail_DownloadDistributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Request Error.
        /// </summary>
        public static string SearchDetail_Exception_NetworkError {
            get {
                return ResourceManager.GetString("SearchDetail_Exception_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SearchDetail_Header {
            get {
                return ResourceManager.GetString("SearchDetail_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string SearchDetail_Install {
            get {
                return ResourceManager.GetString("SearchDetail_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get installed libraries.
        /// </summary>
        public static string SearchDetail_Install_CannotGetLibraries {
            get {
                return ResourceManager.GetString("SearchDetail_Install_CannotGetLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Updated:.
        /// </summary>
        public static string SearchDetail_LatestUpdatedTime {
            get {
                return ResourceManager.GetString("SearchDetail_LatestUpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description not available online.
        /// </summary>
        public static string SearchDetail_ProjectDescription_LoadFailed {
            get {
                return ResourceManager.GetString("SearchDetail_ProjectDescription_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management.
        /// </summary>
        public static string Settings_Category_FileManagement {
            get {
                return ResourceManager.GetString("Settings_Category_FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Settings_Category_Package {
            get {
                return ResourceManager.GetString("Settings_Category_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Source.
        /// </summary>
        public static string Settings_Category_PackageSource {
            get {
                return ResourceManager.GetString("Settings_Category_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Settings_Category_Personalization {
            get {
                return ResourceManager.GetString("Settings_Category_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting Test Versions.
        /// </summary>
        public static string Settings_DetectNonReleaseVersion {
            get {
                return ResourceManager.GetString("Settings_DetectNonReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages that are in Alpha, Beta, etc. test versions will not be ignored.
        /// </summary>
        public static string Settings_DetectNonReleaseVersion_Subtitle {
            get {
                return ResourceManager.GetString("Settings_DetectNonReleaseVersion_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crushes folder not found.
        /// </summary>
        public static string Settings_FileManagement_CrushesDirNotFound {
            get {
                return ResourceManager.GetString("Settings_FileManagement_CrushesDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Folder.
        /// </summary>
        public static string Settings_FileManagement_OpenAppDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenAppDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Crushes Folder.
        /// </summary>
        public static string Settings_FileManagement_OpenCrushesDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenCrushesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Folder.
        /// </summary>
        public static string Settings_FileManagement_OpenLogDir {
            get {
                return ResourceManager.GetString("Settings_FileManagement_OpenLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Config.
        /// </summary>
        public static string Settings_FileManagement_ResetConfig {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all app-related settings. Are you sure you want to keep going with this?.
        /// </summary>
        public static string Settings_FileManagement_ResetConfig_DialogContent {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig_DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All configuration settings (config.json) will be restored to the initial state.
        /// </summary>
        public static string Settings_FileManagement_ResetConfig_Subtitle {
            get {
                return ResourceManager.GetString("Settings_FileManagement_ResetConfig_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared.
        /// </summary>
        public static string Settings_FileManagement_WebViewSettings_CacheCleared {
            get {
                return ResourceManager.GetString("Settings_FileManagement_WebViewSettings_CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView still in use, cannot clear cache.
        /// </summary>
        public static string Settings_FileManagement_WebViewSettings_CacheIsUsing {
            get {
                return ResourceManager.GetString("Settings_FileManagement_WebViewSettings_CacheIsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear WebView2 Cache.
        /// </summary>
        public static string Settings_FileManagement_WebViewSettings_ClearCache {
            get {
                return ResourceManager.GetString("Settings_FileManagement_WebViewSettings_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the WebView2 cache used for e.g. search pages.
        /// </summary>
        public static string Settings_FileManagement_WebViewSettings_ClearCache_Subtitle {
            get {
                return ResourceManager.GetString("Settings_FileManagement_WebViewSettings_ClearCache_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliyun.
        /// </summary>
        public static string Settings_PackageSource_Aliyun {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Aliyun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douban.
        /// </summary>
        public static string Settings_PackageSource_Douban {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Douban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Network.
        /// </summary>
        public static string Settings_PackageSource_NetworkTest {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        public static string Settings_PackageSource_NetworkTestFailed {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string Settings_PackageSource_NetworkTesting {
            get {
                return ResourceManager.GetString("Settings_PackageSource_NetworkTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are in mainland China, we recommend choosing a non-PyPI source.
        /// </summary>
        public static string Settings_PackageSource_Notice {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyPI Official.
        /// </summary>
        public static string Settings_PackageSource_Official {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing and downloading packages via PyPI or other mirror sites.
        /// </summary>
        public static string Settings_PackageSource_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsinghua.
        /// </summary>
        public static string Settings_PackageSource_Tsinghua {
            get {
                return ResourceManager.GetString("Settings_PackageSource_Tsinghua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crush files will be deleted after more than {0} items.
        /// </summary>
        public static string Settings_PersonalizationCrushesAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationCrushesAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files will be deleted after more than {0} items.
        /// </summary>
        public static string Settings_PersonalizationLogAutoDeletion_Tip {
            get {
                return ResourceManager.GetString("Settings_PersonalizationLogAutoDeletion_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_PersonalizationTheme_Dark {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_PersonalizationTheme_Light {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crushes Auto Deletion.
        /// </summary>
        public static string Settings_PersonalizationTitle_CrushesAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_CrushesAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_PersonalizationTitle_Language {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set language.
        /// </summary>
        public static string Settings_PersonalizationTitle_Language_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Language_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Auto Deletion.
        /// </summary>
        public static string Settings_PersonalizationTitle_LogAutoDeletion {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_LogAutoDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the log file number limit.
        /// </summary>
        public static string Settings_PersonalizationTitle_LogAutoDeletion_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_LogAutoDeletion_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_PersonalizationTitle_Theme {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change window theme.
        /// </summary>
        public static string Settings_PersonalizationTitle_Theme_Subtitle {
            get {
                return ResourceManager.GetString("Settings_PersonalizationTitle_Theme_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect after the application is restarted.
        /// </summary>
        public static string Snackbar_effectAfterRestart {
            get {
                return ResourceManager.GetString("Snackbar_effectAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Package.
        /// </summary>
        public static string TrayMenu_Install {
            get {
                return ResourceManager.GetString("TrayMenu_Install", resourceCulture);
            }
        }
    }
}
